In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Решаем уравнение
AX = B, detA != 0, A^-1 = As/detA  (As-союзная матрица-транспонированная матрица алгебраических дополнений A)
(A^-1)AX = (A^-1)B
X = (A^-1)B

In [3]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [4]:
detA = (0 * 9 - 6 * 8) - 2 * (4 * 9 - 6 * 7) + 3 * (4 * 8 - 0 * 7)
detA

60

In [11]:
B = np.array([12, 2, 1])
B

array([12,  2,  1])

Алгебраические дополнения:

In [5]:
A11 = (0 * 9 - 6 * 8)
A12 = -(4 * 9 - 6 * 7)
A13 = (4 * 8 - 0 * 7)
A21 = -(2 * 9 - 8 * 3)
A22 = (1 * 9 - 3 * 7)
A23 = -(1 * 8 - 7 * 2)
A31 = (2 * 6 - 0 * 3)
A32 = -(1 * 6 - 4 * 3)
A33 = (1 * 0 - 4 * 2)

In [7]:
As = np.array([[A11, A21, A31],[A12, A22, A32],[A13, A23, A33]])
As

array([[-48,   6,  12],
       [  6, -12,   6],
       [ 32,   6,  -8]])

In [8]:
Ainv = As / detA  # (A^-1)
Ainv

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [13]:
X = np.dot(Ainv, B)
X

array([-9.2       ,  0.9       ,  6.46666667])

In [14]:
np.dot(A, X)        # Подставим

array([12.,  2.,  1.])