1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [ ]:
import numpy as np

In [11]:
A = np.array([[1, 2, 0], [0, 0, 5],[3, -4, 2], [1, 6, 5], [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [12]:
U, s, W = np.linalg.svd(A)
s

array([8.82486885, 6.14060608, 2.53271528])

In [13]:
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [14]:
A_check = np.dot(np.dot(U, D), V.T)
A_check

array([[ 1.00000000e+00,  2.00000000e+00,  5.69432293e-16],
       [ 1.03164637e-15, -2.16649373e-15,  5.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  6.00000000e+00,  5.00000000e+00],
       [-1.05854814e-16,  1.00000000e+00,  5.52894695e-17]])

In [16]:
#Сингулярное разложение Матрицы A:
print(f"Матрица U:\n {U}")
print(f"Матрица D:\n {D}")
print(f"Матрица V транспонированная:\n {V.T}")

Матрица U:
 [[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
Матрица D:
 [[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Матрица V транспонированная:
 [[ 0.07116451  0.71702467  0.69340553]
 [-0.36737824  0.66514082 -0.65009301]
 [-0.92734505 -0.20847855  0.31075368]]


Евклидова норма матрицы A равна первому сингулярному числу:

In [18]:
print(f"Евклидова норма = {D[0][0]}")

Евклидова норма = 8.824868854820442


Когда известно сингулярное разложение матрицы, ее норма Фробениуса вычисляется как

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [21]:
frobenius = np.sqrt(np.sum(D[np.diag_indices(min(A.shape))]**2))
print(f"Норма Фробениуса = {frobenius}")

Норма Фробениуса = 11.045361017187261
