__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

<h3>Определение:</h3>
Произведением_ матрицы $A = \left\|a_{ij}\right\|$, имеющей порядки $m$ и $n$, и матрицы $B = \left\|b_{ij}\right\|$, имеющей порядки $n$ и $k$, называется матрица $C = \left\|c_{ij}\right\|$, имеющая порядки $m$ и $k$:

$$C = \begin{pmatrix}
c_{11} & c_{12} & \cdots & c_{1k}\\ 
c_{21} & c_{22} & \cdots & c_{2k}\\ 
\cdots & \cdots & \ddots & \cdots\\ 
c_{m1} & c_{m2} & \cdots & c_{mk}
\end{pmatrix},$$

наполненная элементами, определяемыми формулой

$$ c_{ij}=\sum_{p=1}^{n}a_{ip}b_{pj}.$$<br>
<h3>Ограничение:</h3><br>
Следует заметить, что матрицу $A$ можно умножить не на всякую матрицу $B$: необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$ - здесь произведения $AB$ и $BA$ не определены.

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;- здесь произведение $AB$ определено, размерность результирующей матрицы $2\times 3$.<br>
Произведение $BA$ не определено.

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; - здесь произведение $AB$ определено, размерность результирующей матрицы $8\times 8$.<br>
произведение $BA$ определено, размерность результирующей матрицы $3\times 3$.<br>

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. - здесь произведения $AB$ и $BA$ определены, размерность результирующих матриц $4\times 4$.<br>

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [3]:
def print_matrix(m: list):
    for i in range(len(m)):
        print(m[i])

#функция для сложения матриц
def matrix_sum(m1: list, m2: list):
    if (len(m1) != len(m2)) or (len(m1[0]) != len(m2[0])):
        print("Сумма не опредеоена: разные матрицы")
        return
    ms = [[0 for _ in range(len(m1[0]))] for _ in range(len(m1))]
    for i in range(len(m1)):
        for j in range(len(m1[0])):
            ms[i][j] = m1[i][j] + m2[i][j]
    return ms

# функция умножения матрицы на число
def matrix_dig_mult(a: list, d):
    ad = [[0 for _ in range(len(a[0]))] for _ in range(len(a))]
    for i in range(len(a)):
        for j in range(len(a[0])):
            ad[i][j] = a[i][j] * d
    return ad

# функция для умножения матриц
def matrix_mult(a1: list, a2: list):
    if len(a1[0]) != len(a2):
        print("Произведение не определено")
        return
    m = len(a1)
    n = len(a2)
    k = len(a2[0])
    amult = [[0 for _ in range(k)] for _ in range(m)]
    for p in range(k):
        for i in range(m):
            for j in range(n):
                amult[i][p] += a1[i][j] * a2[j][p]
    return amult

# функция для транспонирования матрицы
def matrix_transp(a: list):
    at = [[0 for _ in range(len(a))] for _ in range(len(a[0]))]
    for i in range(len(a)):
        for j in range(len(a[0])):
            at[j][i] = a[i][j]
    return at
            

In [4]:
m1 = [[1, -2], 
      [3, 0]]
m2 = [[4, -1], 
      [0, 5]]
print_matrix(matrix_sum(m1, m2))

[5, -3]
[3, 5]


In [5]:
print_matrix(matrix_mult(m1, m2))

[4, -11]
[12, -3]


In [6]:
#проверим в numpy
import numpy as np
a1 = np.array(m1)
a2 = np.array(m2)
np.dot(a1, a2)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [12]:
a = [[1, 7],
     [3, -6]]
b = [[0, 5],
    [2, -1]]
c = [[2, -4],
    [1, 1]]

In [13]:
a3 = matrix_dig_mult(a, 3)
#здесь умножается сразу на -2
b2 = matrix_dig_mult(b, -2)
c4 = matrix_dig_mult(c, 4)

In [15]:
line_comb = matrix_sum(a3, matrix_sum(b2, c4))
print_matrix(line_comb)

[11, -5]
[9, -12]


In [17]:
#проверим в numpy
aa = np.array(a)
bb = np.array(b)
cc = np.array(c)
line_comb1 = 3 * aa - 2 * bb + 4 * cc
print(line_comb1)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [22]:
A = [[4, 1], 
     [5, -2], 
     [2, 3]]
AT = matrix_transp(A)
print_matrix(AT)

[4, 5, 2]
[1, -2, 3]


In [23]:
AAT = matrix_mult(A, AT)
print_matrix(AAT)

[17, 18, 11]
[18, 29, 4]
[11, 4, 13]


In [27]:
ATA = matrix_mult(AT, A)
print_matrix(ATA) 

[45, 0]
[0, 14]


In [29]:
#проверим вnumpy
AA = np.array(A)
AA

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [30]:
AA.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [31]:
np.dot(AA, AA.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [32]:
np.dot(AA.T, AA)

array([[45,  0],
       [ 0, 14]])

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

Функция для умножения матриц<br>
def matrix_mult(a1: list, a2: list) - определена выше

In [34]:
#функции для вычисления определителя (не хочется считать)
# вычеркиваем i-тую строку и  j-тый столбец
def matrix_low(a: list, ii: int, jj: int):
    n = len(a)
    al = [[0 for _ in range(n - 1)] for _ in range(n - 1)]
    k = 0
    for i in range(n):
        if i == ii:
            continue
        p = 0
        for j in range(n):
            if j == jj:
                continue
            al[k][p] = a[i][j]
            p += 1
        k += 1
    return al


# определитепль
def det(a: list):
    if len(a) == 2:
        return (a[0][0] * a[1][1]) - (a[0][1] * a[1][0])
    d = 0
    for j in range(len(a)):
        d += (-1)**(0 + j) * det(matrix_low(a, 0, j)) * a[0][j]
    return d

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) в первом случае определитель раве 1

б) во втором случае определитель равен произведению элементов на главной диагонали = 180 (треугольная матрица)

In [38]:
# в) здесь посчитаем
a = [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
deta = det(a)
print(deta)

0


In [39]:
#проверим в numpy 
aa = np.array(a)
np.linalg.det(aa)

-9.51619735392994e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

Учитывая следующие свойства определителя

__1.__ Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA.$$

__2.__ Для двух квадратных матриц одинакового размера

$$det(AB)=detA\cdot detB.$$

__3.__ Если квадратная матрица $A$ $n\times n$ n-го порядка умножается на некоторое ненулевое число $λ$, то определитель полученной матрицы равен произведению определителя исходной матрицы $A$ на число $λ$ в степени, равной порядку матрицы<br>
$|λ \cdot A| = λ^{n}\cdot |A|$


a) в первом случае определитель = 16

б) в втором случае определитель = 4

в) в третьем случае определитель = $2^{n}\cdot 4, n-$ порядок матрицы, 

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


Матрица - вырожденная, если её определитель равен 0<br>
В данном случае 1 и 2 строка матрицы являются линейно зависимыми<br>
$-2\cdot\begin{pmatrix}
-2 & 7 & -3\end{pmatrix} = \begin{pmatrix}
4 & -14 & 6\end{pmatrix}$<br>
Если строки в матрице линейно зависимы, то её определитель равен 0, значит эта матрица вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) матрице $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$<br>
3-я строка является суммой первой и второй строк её можно вычеркнуть и тогда останется<br>
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$<br>
далее вычесть вторую строку из первой, получится $\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1
\end{pmatrix}$ - здесь ранг равен 2<br>

 б) в матрице $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ третья строка равна сумме первой и второй строки, её можно вычеркнуть,<br>
останется
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$
здесь ранг равен 3