In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Cобственные значения линейного оператора - корни характеристическое уравнение:<br>
$(-1-\lambda)(6-\lambda) + 12=0$<br>
$\lambda^{2} - 5\lambda + 6 =0$<br>
$\lambda=(2,  3)$ - собственные значения.<br>

Найдем собственные векторы вида 
$\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
2
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$

Получим

$\begin{cases}
-3x_{1}-6x_{2}= 0, \\
2x_{1}+4x_{2}= 0.
\end{cases}$ 

получается $x_1 = -2x_2$, т.е множество вектров подчиняющееся  этому равенству, например<br>
$x_1 = -2, x_2 = 1$ <br>
Проверим:

In [ ]:
A = np.array([[-1, -6],[2, 6]])
x = np.array([[-2], [1]])

In [3]:
Ax = np.dot(A, x)
Ax

array([[-4],
       [ 2]])

получилось.

Теперь возьмём $\lambda = 3$:<br>
Получим

$\begin{cases}
-4x_{1}-6x_{2}= 0, \\
2x_{1}+3x_{2}= 0.
\end{cases}$ 

получается $x_1 = -\frac{3}{2}x_2$ т.е множество вектров подчиняющееся  этому равенству, например<br>
$x_1 = 3, x_2 = -2$ <br>
Проверим:

In [5]:
x = np.array([[3], [-2]])
Ax = np.dot(A, x)
Ax

array([[ 9],
       [-6]])

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.


Собственное число для этого оператора $\lambda = -1$

нужно показать что $\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}\cdot\begin{pmatrix}x_1\\x_2\end{pmatrix} = -\begin{pmatrix}x_1\\x_2\end{pmatrix}$

получается что $-x_1 = -x_1,  -x_2 = -x_2$, то есть любой вектор для этого оператора является собственным.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Найдём собственные числа:<br>
$\lambda=2$

теперь проверим что $\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}\cdot\begin{pmatrix}1\\1\end{pmatrix} = 2\begin{pmatrix}1\\1\end{pmatrix}$

In [6]:
A = np.array([[1, 1],[-1, 3]])
x = np.array([[1], [1]])

In [7]:
Ax = np.dot(A, x)
Ax

array([[2],
       [2]])

Равенство выполняется, значит вектор $x=(1,1)$​ является собственным для этого оператора.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора. Тогда:

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$

$
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$


Одинаковой $\lambda$ не получилось значит вектор $x=(3, -3, -4)$ ня является собственным.<br>
Проверим на всякий случай:

In [9]:
A = np.array([[0, 3, 0],[3, 0, 0],[0, 0, 3]])
x = np.array([[3], [-3], [-4]])

In [10]:
Ax = np.dot(A, x)
Ax

array([[ -9],
       [  9],
       [-12]])