__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

In [1]:
import numpy as np

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 &  1\\ 
1 & 1 & -3 &  1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$
после преобразований получаем
$\begin{pmatrix}
\left.\begin{matrix}
1 &  1 & -1 & -2\\ 
0 & -1 &  1 &  5\\ 
0 &  0 & -2 &  3
\end{matrix}\right|
\begin{matrix}
 0\\ 
-2\\
 4
\end{matrix}
\end{pmatrix}$<br><br>
выражаем всё через $x_{4}$<br>
$x_{3} = \frac{3x_{4} - 4}{2}$<br>
$x_{2} = \frac{13x_{4}}{2}$<br>
$x_{1} = -\frac{{10x_{4} + 4}}{{2}}$<br>

полагаем $x_{4} = t$ тогда<br>

$x_{3} = \frac{3t - 4}{2}$<br>
$x_{2} = \frac{13t}{2}$<br>
$x_{1} = -\frac{{6t + 4}}{{2}}$<br>

In [9]:
#проверим
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
A

array([[ 1,  1, -1, -2],
       [ 2,  1, -1,  1],
       [ 1,  1, -3,  1]])

In [25]:
#возьмём
t = 2
x3 = (3 * t - 4) / 2
x2 = (13 * t) / 2
x1 = -((6 * t + 4) / 2)
x = np.array([[x1], [x2], [x3], [t]])
x

array([[-8.],
       [13.],
       [ 1.],
       [ 2.]])

In [26]:
b = np.dot(A, x)
b

array([[ 0.],
       [-2.],
       [ 4.]])

Получается, система уравнений имеет бесконечное множество решений.

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [ ]:
#первая система
A1 = np.array([[3, -1, 1],[2, -5, -3], [1, 1, -1]])
A1

In [30]:
#найдём определитель
detA1 = np.linalg.det(A1)
detA1

32.0

Определитель больше нуля значит система имеет хотя бы одно решение значит она СОВМЕСТНА
Так число неизвестных равно размерности матрицы коэффициэнтов то решение единственное:<br>
$x_{1} = 1, x_{2} = 2, x_{3} = 3$

In [36]:
#проверим
x = np.array([[1], [2], [3]])
b = np.dot(A1, x)
b

array([[  4],
       [-17],
       [  0]])

получилось!

 б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

Здесь определитель можно не считать ( = 0), строки и столбцы матрицы - линейно зависимы.
Система НЕСОВМЕСТНА так как не имеет ни одного решения (если бы была однородной имела бы одно решение - нулевое).

 в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [48]:
#третья система
A3 = np.array([[1, 2, 5],[3, 1, -8]])
A3

array([[ 1,  2,  5],
       [ 3,  1, -8]])

In [51]:
t = 0
x3 = t
x2 = (14 - 23 * t) / 5
x1 = 4 - ((28 - 21*t) / 5)
x = np.array([[x1], [x2], [x3]])
x

array([[-1.6],
       [ 2.8],
       [ 0. ]])

In [52]:
b = np.dot(A3, x)
b

array([[ 4.],
       [-2.]])

Система СОВМЕСТНА и имеет бесконечное множество решений

_3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Применим терему Кронекера- Капелли

In [59]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0],[0, 0, 0, 2]])
Aex = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4],[0, 0, 0, 2, 1]])

In [60]:
n = 4
rankA = np.linalg.matrix_rank(A)
rankA

4

In [61]:
rankAex = np.linalg.matrix_rank(Aex)
rankAex

4

$rankA=rankAex=n$, и $n$ это число неизвестных, в этом случае система имеет единственное решение и значит она СОВМЕСТНА ;<br>

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Система будет несовмествной при любых $a$, $b$ и $c$ одновременно не равных нулю.

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Метод Крамера:
Для системы с $n$ уравнениями и $n$ неизвестными, если система уравнений невырождена (то есть $detA\neq 0$), то система определена, то есть имеет единственное решение, и это решение может быть найдено по формулам Крамера:

$$x_{i}=\frac{detA_{i}}{detA},$$

где $A_{i}$ — это матрица, получаемая заменой $i$-го столбца на вектор-столбец свободных членов $b$.

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [84]:
A = np.array([[1, -2], [3, -4]])
detA = np.linalg.det(A)
detA

2.0000000000000004

In [86]:
#определитель не равен 0 - можно продолжать
A1 = np.array([[1, -2], [7, -4]])
detA1 = np.linalg.det(A1)
detA1

9.999999999999998

In [88]:
A2 = np.array([[1, 1], [3, 7]])
detA2 = np.linalg.det(A2)
detA2

4.0

In [89]:
x1 = detA1 / detA
x2 = detA2 / detA
print(x1, x2)

4.999999999999998 1.9999999999999996


In [90]:
#проверим
x = np.array([[x1], [x2]])
b = np.dot(A, x)
b

array([[1.],
       [7.]])

заавтоматизируем метод Крамера

In [95]:
def matrix_low(a: list, ii: int, jj: int):
    n = len(a)
    al = [[0 for _ in range(n - 1)] for _ in range(n - 1)]
    k = 0
    for i in range(n):
        if i == ii:
            continue
        p = 0
        for j in range(n):
            if j == jj:
                continue
            al[k][p] = a[i][j]
            p += 1
        k += 1
    return al


# определитепль
def det(a: list):
    if len(a) == 2:
        return (a[0][0] * a[1][1]) - (a[0][1] * a[1][0])
    d = 0
    for j in range(len(a)):
        d += (-1)**(0 + j) * det(matrix_low(a, 0, j)) * a[0][j]
    return d


def kramer(a: list, b: list) -> list:
    n = len(a)
    al = [[a[i][j] for j in range(n)] for i in range(n)]
    det_al = det(al)
    if det_al == 0:
        print("Решений нет")
        return None
    x = []
    for i in range(n):
        for j in range(n):
            al[j][i] = b[j]
        x.append(det(al) / det_al)
        for j in range(n):
            al[j][i] = a[j][i]
    return x

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [100]:
#проверим Крамера
A = [[2, -1, 5], [1, 1, -3], [2, 4, 1]]
b = [10, -2, 1]

In [97]:
x = kramer(A, b)
x

3


[2.0, -1.0, 1.0]

In [99]:
#проверим правильность в numpy
AA = np.array(A)
xx = np.array([[2], [-1], [1]])
b = np.dot(AA, xx)
b

array([[10],
       [-2],
       [ 1]])

Получилось!